/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package first;
import java.sql.*;
// import java.util.Scanner;

public class App {
    public String getGreeting() throws Exception {
        return "Hello World!";
    }
    public static void main(String[] args) throws Exception{
          // Load database driver in memory 

          System.out.println("Driver Loaded");
  
          Connection conn ;
          conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/test1", "postgresql", "root");
  
          System.out.println("Connection done");
  
          Statement stmt ;
          stmt = conn.createStatement();
  
          String sql;
          sql = "insert into student values(700,'testing')";
  
          stmt.executeUpdate(sql);
          System.out.println("Record inserted");
  
        //   Scanner sc = new Scanner(System.in);
        //   String id = sc.nextLine();
        //   String name = sc.nextLine();
  
        //   sql = "insert into student ("+id+" ,'"+name+"')";
        // //   stmt.executeUpdate(id);
        // //   stmt.executeUpdate(name); 
          stmt.executeUpdate(sql);
  
          conn.close();
        //   sc.close();
    }
}
