/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package second;
import java.sql.*;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        System.out.println("Driver Loaded");

        Connection conn ;
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/test1","postgresql","root");

        System.out.println("Connection done");

        Statement stmt;
        stmt = conn.createStatement();

        String sql; 
        sql = "insert into student values(1,'OneNumber')";

        stmt.executeUpdate(sql);
        System.out.println("Record inserted");
        conn.close();


    }
}
