/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package first;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() throws Exception {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}



